In [7]:
import numpy as np

vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(vector1)
print(vector2)

print("Addition: ", vector1 + vector2)

result3 = np.dot(vector2,vector1)
result4 = np.cross(vector1, vector2)
print(result3, result4)

matrix1 = ([
    [1,2,3],
    [4,5,6]
])

print(matrix1)

[1 2 3]
[4 5 6]
Addition:  [5 7 9]
32 [-3  6 -3]
[[1, 2, 3], [4, 5, 6]]


In [2]:
import numpy as np

n = 3  # Size of matrix

identity_matrix = np.eye(n)  # Create Identity Matrix

print(identity_matrix)

matrix1 = np.array([[101,21,3],
                    [0,19,0],
                    [10,1,0]])
 
rank1 = np.linalg.matrix_rank(matrix1)
print("Rank is:", rank1)

# To find determinent of Matrix
detA = np.linalg.det(matrix1)
print(detA)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Rank is: 3
-570.0000000000002
